spring.application.name=api

# server config.
server.port=5000

# database config.
spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.driver-class-name=org.postgresql.Driver

